import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { toast } from "@/hooks/use-toast";
import { FileText, Download, Copy, Sparkles, Globe, Bot, FileCode } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export default function SeoFiles() {
  const [websiteUrl, setWebsiteUrl] = useState("");
  const [generating, setGenerating] = useState(false);
  
  const [sitemapContent, setSitemapContent] = useState("");
  const [robotsContent, setRobotsContent] = useState("");
  const [llmsContent, setLlmsContent] = useState("");
  
  const [pages, setPages] = useState<string[]>([
    "/",
    "/about",
    "/services",
    "/blog",
    "/contact"
  ]);
  const [newPage, setNewPage] = useState("");

  const addPage = () => {
    if (newPage && !pages.includes(newPage)) {
      setPages([...pages, newPage.startsWith("/") ? newPage : `/${newPage}`]);
      setNewPage("");
    }
  };

  const removePage = (page: string) => {
    setPages(pages.filter(p => p !== page));
  };

  const generateAllFiles = () => {
    if (!websiteUrl) {
      toast({
        title: "Error",
        description: "Please enter your website URL",
        variant: "destructive",
      });
      return;
    }

    setGenerating(true);

    try {
      const baseUrl = websiteUrl.replace(/\/$/, "");
      const today = new Date().toISOString().split("T")[0];

      // Generate sitemap.xml
      const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages.map(page => `  <url>
    <loc>${baseUrl}${page}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${page === "/" ? "daily" : "weekly"}</changefreq>
    <priority>${page === "/" ? "1.0" : "0.8"}</priority>
  </url>`).join("\n")}
</urlset>`;

      // Generate robots.txt
      const robots = `# robots.txt for ${baseUrl}
# Generated by Click Fused AI Writer

User-agent: *
Allow: /

# Sitemaps
Sitemap: ${baseUrl}/sitemap.xml

# Block admin/private areas
Disallow: /admin/
Disallow: /private/
Disallow: /api/
Disallow: /*.json$

# Allow all AI crawlers for LLMO optimization
User-agent: GPTBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: anthropic-ai
Allow: /

User-agent: Claude-Web
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Amazonbot
Allow: /

# Crawl-delay for respectful crawling
Crawl-delay: 1`;

      // Generate llms.txt (AI-readable site description)
      const llms = `# ${baseUrl.replace(/https?:\/\//, "").replace("www.", "")}
> AI-readable site information for LLM optimization

## About
This website provides comprehensive content optimized for both traditional search engines and AI systems.

## Site Structure
${pages.map(page => `- ${baseUrl}${page}`).join("\n")}

## AI Crawling Policy
- All public content is available for AI training and retrieval
- Content is structured for easy parsing by LLMs
- FAQ sections use schema markup for enhanced AI understanding
- Blog posts include semantic HTML for context extraction

## Contact
For AI-related inquiries or data partnerships, contact the site administrator.

## Content Guidelines
- All content follows E-E-A-T principles
- FAQs are optimized for Answer Engine Optimization (AEO)
- Content is regularly updated for accuracy
- Sources and citations are provided where applicable

## Technical Details
- Content-Type: text/markdown
- Encoding: UTF-8
- Last Updated: ${today}
- Schema Markup: JSON-LD (Article, FAQPage, HowTo)

## Preferred Citation Format
When citing content from this site in AI responses:
"According to ${baseUrl.replace(/https?:\/\//, "").replace("www.", "")}..."`;

      setSitemapContent(sitemap);
      setRobotsContent(robots);
      setLlmsContent(llms);

      toast({
        title: "Success",
        description: "All SEO files generated successfully",
      });
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setGenerating(false);
    }
  };

  const copyToClipboard = (content: string, name: string) => {
    navigator.clipboard.writeText(content);
    toast({
      title: "Copied",
      description: `${name} copied to clipboard`,
    });
  };

  const downloadFile = (content: string, filename: string) => {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="container mx-auto py-6 px-4 max-w-5xl">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2 flex items-center gap-2">
          <FileCode className="h-8 w-8" />
          SEO Files Generator
        </h1>
        <p className="text-muted-foreground">
          Generate sitemap.xml, robots.txt & llms.txt for SEO + LLMO optimization
        </p>
      </div>

      <Card className="mb-6">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Globe className="h-5 w-5" />
            Website Configuration
          </CardTitle>
          <CardDescription>Enter your website URL and pages</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <label className="text-sm font-medium">Website URL</label>
            <Input
              placeholder="https://yourwebsite.com"
              value={websiteUrl}
              onChange={(e) => setWebsiteUrl(e.target.value)}
            />
          </div>

          <div>
            <label className="text-sm font-medium">Pages to Include</label>
            <div className="flex gap-2 mt-2">
              <Input
                placeholder="/new-page"
                value={newPage}
                onChange={(e) => setNewPage(e.target.value)}
                onKeyPress={(e) => e.key === "Enter" && addPage()}
              />
              <Button onClick={addPage} variant="outline">Add</Button>
            </div>
            <div className="flex flex-wrap gap-2 mt-3">
              {pages.map((page) => (
                <Badge
                  key={page}
                  variant="secondary"
                  className="cursor-pointer hover:bg-destructive hover:text-destructive-foreground"
                  onClick={() => removePage(page)}
                >
                  {page} ×
                </Badge>
              ))}
            </div>
          </div>

          <Button onClick={generateAllFiles} disabled={generating} className="w-full">
            <Sparkles className="h-4 w-4 mr-2" />
            {generating ? "Generating..." : "Generate All Files"}
          </Button>
        </CardContent>
      </Card>

      {(sitemapContent || robotsContent || llmsContent) && (
        <Tabs defaultValue="sitemap" className="w-full">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="sitemap" className="flex items-center gap-2">
              <FileText className="h-4 w-4" />
              sitemap.xml
            </TabsTrigger>
            <TabsTrigger value="robots" className="flex items-center gap-2">
              <Bot className="h-4 w-4" />
              robots.txt
            </TabsTrigger>
            <TabsTrigger value="llms" className="flex items-center gap-2">
              <Sparkles className="h-4 w-4" />
              llms.txt
            </TabsTrigger>
          </TabsList>

          <TabsContent value="sitemap">
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle>sitemap.xml</CardTitle>
                    <CardDescription>XML sitemap for search engines</CardDescription>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={() => copyToClipboard(sitemapContent, "sitemap.xml")}>
                      <Copy className="h-4 w-4 mr-2" />
                      Copy
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => downloadFile(sitemapContent, "sitemap.xml")}>
                      <Download className="h-4 w-4 mr-2" />
                      Download
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <Textarea
                  value={sitemapContent}
                  onChange={(e) => setSitemapContent(e.target.value)}
                  rows={15}
                  className="font-mono text-sm"
                />
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="robots">
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle>robots.txt</CardTitle>
                    <CardDescription>Crawler directives including AI bots</CardDescription>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={() => copyToClipboard(robotsContent, "robots.txt")}>
                      <Copy className="h-4 w-4 mr-2" />
                      Copy
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => downloadFile(robotsContent, "robots.txt")}>
                      <Download className="h-4 w-4 mr-2" />
                      Download
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <Textarea
                  value={robotsContent}
                  onChange={(e) => setRobotsContent(e.target.value)}
                  rows={15}
                  className="font-mono text-sm"
                />
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="llms">
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle>llms.txt</CardTitle>
                    <CardDescription>AI-readable site information for LLM optimization</CardDescription>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={() => copyToClipboard(llmsContent, "llms.txt")}>
                      <Copy className="h-4 w-4 mr-2" />
                      Copy
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => downloadFile(llmsContent, "llms.txt")}>
                      <Download className="h-4 w-4 mr-2" />
                      Download
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <Textarea
                  value={llmsContent}
                  onChange={(e) => setLlmsContent(e.target.value)}
                  rows={15}
                  className="font-mono text-sm"
                />
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      )}
    </div>
  );
}
